export const initialState = {
  products: {
    data: [
      {
        id: 1,
        title: 'Watermelon Lolipop',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/watermelonLollipop.jpg' ,
        imgCart: '/img/smallImg/watermelonLollipopSmall.jpg',
        flavour: 'fruit',
        price: 10,
        inCart: false,
      },
      {
        id: 2,
        title: 'Hard Candy Mix',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/hart.jpg',
        imgCart: '/img/smallImg/hartSmall.jpg',
        flavour: 'fruit',
        price: 16,
        inCart: true,
      },
      {
        id: 3,
        title: 'Rainbbow jelly',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/rainbowJelly2.jpg',
        imgCart: '/img/smallImg/rainbowJelly2Small.jpg',
        flavour: 'fruit',
        price: 8,
        inCart: false,
      },
      {
        id: 4,
        title: 'Strawberry Kisses',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/colaJelly.jpg',
        imgCart: '/img/smallImg/colaJellySmall.jpg',
        flavour: 'fruit',
        price: 18,
        inCart: false,
      },
      {
        id: 5,
        title: 'Chewwing Gum',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/HartCandy.jpg',
        imgCart: '/img/smallImg/HartCandySmall.jpg',
        flavour: 'mix',
        price: 24,
        inCart: false,
      },
      {
        id: 6,
        title: 'Mint hard candy',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/mintOnPlate.jpg',
        imgCart: '/img/smallImg/mintOnPlateSmall.jpg',
        flavour: 'traditional',
        price: 17,
        inCart: false,
      },
      {
        id: 7,
        title: 'Hart Candy',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/chocolateLolipop.jpg',
        imgCart: '/img/smallImg/chocolateLolipopSmall.jpg',
        flavour: 'fruit',
        price: 30,
        inCart: false,
      },
      {
        id: 8,
        title: 'Coca-cola jelly',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/frutmix.jpg',
        imgCart: '/img/smallImg/frutmixSmall.jpg',
        flavour: 'fruit',
        price: 2,
        inCart: false,
      },
      {
        id: 9,
        title: 'Mint hard candy',
        description:  'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.',
        images: '/img/mail.ajpg',
        imgCart: '/img/mix.jpg',
        flavour: 'traditional',
        price: 17,
        inCart: false,
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};